package com.iti.model.entity;
// Generated Mar 23, 2019 1:04:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CartItemDao generated by hbm2java
 */
@Entity
@Table(name="cart_item",catalog="toysonlineshoppingdb")
public class CartItem implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="item_id", unique=true, nullable=false)
    private Integer itemID;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="products_id", nullable=false)
    private Product products;
    @Column(name="quantity", nullable=false)
    private int quantity;
    @Column(name="total_cost", nullable=false, precision=6, scale=3)
    private BigDecimal totalCost;
    @ManyToMany(fetch=FetchType.LAZY, mappedBy="shoppingCartItems")
    private Set<ShoppingCart> shoppingCarts = new HashSet<>(0);

    public CartItem() {
    }
    public CartItem(Product products, int quantity, BigDecimal totalcost) {
        this.products = products;
        this.quantity = quantity;
        this.totalCost = totalcost;
    }
    public CartItem(Product products, int quantity, BigDecimal totalcost, Set shoppingcarts) {
        this.products = products;
        this.quantity = quantity;
        this.totalCost = totalcost;
        this.shoppingCarts = shoppingcarts;
    }
    public Integer getItemID() {
        return this.itemID;
    }
    public void setItemID(Integer itemID) {
        this.itemID = itemID;
    }
    public Product getProducts() {
        return this.products;
    }
    public void setProducts(Product products) {
        this.products = products;
    }
    public int getQuantity() {
        return this.quantity;
    }
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getTotalCost() {
        return this.totalCost;
    }
    public void setTotalCost(BigDecimal totalCost) {
        this.totalCost = totalCost;
    }
    public Set getShoppingCarts() {
        return this.shoppingCarts;
    }
    public void setShoppingCarts(Set shoppingCarts) {
        this.shoppingCarts = shoppingCarts;
    }

}


