package com.iti.model.entity;
// Generated Mar 23, 2019 1:04:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * OrderHistory generated by hbm2java
 */
@Entity
@Table(name="order_history",catalog="toysonlineshoppingdb")
public class OrderHistory implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="order_history_id", unique=true, nullable=false)
    private Integer orderHistoryID;

    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="timestamp", nullable=false, length=26)
    private Date timestamp;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    private User user;

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="order_history_products", catalog="toysonlineshoppingdb",
            joinColumns = {@JoinColumn(name="products_id", nullable=false, updatable=false) },
            inverseJoinColumns = {@JoinColumn(name="order_history_id", nullable=false, updatable=false) })
    private Set<Product> orderHistoryProducts = new HashSet(0);

    public OrderHistory() {}
    public OrderHistory(User user) {
        this.user = user;
    }
    public OrderHistory(User user, Set productses) {
        this.user = user;
        this.orderHistoryProducts = productses;
    }

    public Integer getOrderHistoryID() {
        return orderHistoryID;
    }

    public void setOrderHistoryID(Integer orderHistoryID) {
        this.orderHistoryID = orderHistoryID;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Set getOrderHistoryProducts() {
        return orderHistoryProducts;
    }

    public void setOrderHistoryProducts(Set orderHistoryProducts) {
        this.orderHistoryProducts = orderHistoryProducts;
    }
}


