package com.iti.model.entity;
// Generated Mar 23, 2019 1:04:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReviewId generated by hbm2java
 */
@Embeddable
public class ReviewId implements java.io.Serializable {

    @Column(name="user_id", nullable=false, length=50)
    private String userId;
    @Column(name="products_id", nullable=false)
    private int productsId;


    public ReviewId() {
    }

    public ReviewId(String userId, int productsId, int rate) {
        this.userId = userId;
        this.productsId = productsId;
    }



    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }


    public int getProductsId() {
        return this.productsId;
    }

    public void setProductsId(int productsId) {
        this.productsId = productsId;
    }



    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof ReviewId) ) return false;
        ReviewId castOther = ( ReviewId ) other;

        return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
                && (this.getProductsId()==castOther.getProductsId());
    }

    public int hashCode() {
        int result = 17;
        result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
        result = 37 * result + this.getProductsId();

        return result;
    }


}


