package com.iti.model.entity;
// Generated Mar 23, 2019 1:04:18 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name="review",catalog="toysonlineshoppingdb")
public class Review  implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides( {
            @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false, length=50) ),
            @AttributeOverride(name="productsId", column=@Column(name="products_id", nullable=false) )
    } )
    private ReviewId id;

    @Column(name="rate", nullable=false)
    private int rate;

    @Column(name="review_description", nullable=true, length=1000)
    private String reviewDescription;


    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="products_id", nullable=false, insertable=false, updatable=false)
    private Product products;


    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    private User user;

    public Review() {
    }
    public Review(ReviewId id, Product products, User user, String reviewdescription) {
        this.id = id;
        this.products = products;
        this.user = user;
        this.reviewDescription = reviewdescription;
    }

    public int getRate() {
        return rate;
    }

    public void setRate(int rate) {
        this.rate = rate;
    }

    public ReviewId getId() {
        return id;
    }

    public void setId(ReviewId id) {
        this.id = id;
    }

    public Product getProducts() {
        return products;
    }

    public void setProducts(Product products) {
        this.products = products;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getReviewDescription() {
        return reviewDescription;
    }

    public void setReviewDescription(String reviewDescription) {
        this.reviewDescription = reviewDescription;
    }
}


