package com.iti.model.entity;
// Generated Mar 23, 2019 1:04:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShoppingCart generated by hbm2java
 */
@Entity
@Table(name="shopping_cart",catalog="toysonlineshoppingdb"
)
public class ShoppingCart implements java.io.Serializable {
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="cart_id", unique=true, nullable=false)
    private Integer cartId;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    private User user;
    @Column(name="total_cost", nullable=false, precision=6, scale=3)
    private BigDecimal totalCost;
    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="shopping_cart_items", catalog="toysonlineshoppingdb",
            joinColumns = {@JoinColumn(name="cart_id", nullable=false, updatable=false) },
            inverseJoinColumns = {@JoinColumn(name="items_id", nullable=false, updatable=false) })
    private Set<CartItem> shoppingCartItems = new HashSet<>(0);

    public ShoppingCart() {
    }
    public ShoppingCart(User user, BigDecimal totalcost) {
        this.user = user;
        this.totalCost = totalcost;
    }
    public ShoppingCart(User user, BigDecimal totalcost, Set itemses) {
        this.user = user;
        this.totalCost = totalcost;
        this.shoppingCartItems = itemses;
    }

    public Integer getCartId() {
        return this.cartId;
    }

    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    public BigDecimal getTotalCost() {
        return this.totalCost;
    }

    public void setTotalCost(BigDecimal totalCost) {
        this.totalCost = totalCost;
    }

    public Set getShoppingCartItems() {
        return this.shoppingCartItems;
    }

    public void setShoppingCartItems(Set shoppingCartItems) {
        this.shoppingCartItems = shoppingCartItems;
    }




}


