package com.iti.model.entity;
// Generated Mar 23, 2019 1:04:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ShoppingCart generated by hbm2java
 */
@Entity
@Table(name="shopping_cart",catalog="toysonlineshoppingdb"
)
public class ShoppingCart implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="cart_id", unique=true, nullable=false)
    private Integer cartId;
    @Column(name="total_cost", nullable=false, precision=6, scale=3)
    private Double totalCost;

    @OneToOne(mappedBy="shoppingCart",cascade = CascadeType.ALL)
    private User user;

    @ManyToMany(fetch=FetchType.LAZY,cascade = CascadeType.ALL)
    @JoinTable(name="shopping_cart_items", catalog="toysonlineshoppingdb",
            joinColumns = {@JoinColumn(name="cart_id", nullable=false, updatable=false) },
            inverseJoinColumns = {@JoinColumn(name="items_id", nullable=false, updatable=false) })
    private Set<CartItem> shoppingCartItems = new HashSet<>(0);

    public ShoppingCart() {
    }

    public Integer getCartId() {
        return cartId;
    }

    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    public Double getTotalCost() {
        return totalCost;
    }

    public void setTotalCost(Double totalCost) {
        this.totalCost = totalCost;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Set<CartItem> getShoppingCartItems() {
        return shoppingCartItems;
    }

    public void setShoppingCartItems(Set<CartItem> shoppingCartItems) {
        this.shoppingCartItems = shoppingCartItems;
    }
}


