package com.iti.model.entity;
// Generated Mar 23, 2019 1:04:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name="store",catalog="toysonlineshoppingdb")
public class Store implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="store_id", unique=true, nullable=false)
    private Integer storeID;
    @Column(name="name", nullable=false, length=50)
    private String name;

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="stores_products", catalog="toysonlineshoppingdb",
            joinColumns = {@JoinColumn(name="stores_id", nullable=false, updatable=false) },
            inverseJoinColumns = {@JoinColumn(name="products_id", nullable=false, updatable=false) })
    private Set<Product> storeProducts = new HashSet(0);

    public Integer getStoreID() {
        return storeID;
    }

    public void setStoreID(Integer storeID) {
        this.storeID = storeID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getStoreProducts() {
        return storeProducts;
    }

    public void setStoreProducts(Set storeProducts) {
        this.storeProducts = storeProducts;
    }
}


