package com.iti.model.entity;
// Generated Mar 23, 2019 1:04:18 PM by Hibernate Tools 4.3.1
import java.math.BigDecimal;
import java.util.*;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user",catalog="toysonlineshoppingdb")
public class User  implements java.io.Serializable {

    @Id
    @Column(name="email", unique=true, nullable=false, length=50)
    private String email;

    @Column(name="name", nullable=false, length=50)
    private String name;

    @Column(name="password", nullable=false, length=40)
    private String password;

    @Column(name="birth_date", nullable=false, length=10)
    private Date birthDate;

    @Column(name="job", nullable=false, length=50)
    private String job;

    @Column(name="address", nullable=false, length=100)
    private String address;

    @Column(name="credit_limit", nullable=false, precision=6, scale=3)
    private BigDecimal creditLimit;

    @Column(name="image_path", nullable=false, length=50)
    private String imagePath;

    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    private Set<Review> reviews = new HashSet(0);

    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    private Set<OrderHistory> orderHistories = new HashSet(0);

    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    private Set<ShoppingCart> shoppingCarts = new HashSet(0);

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_products", catalog="toysonlineshoppingdb",
            joinColumns = {@JoinColumn(name="user_id", nullable=false, updatable=false) },
            inverseJoinColumns = {@JoinColumn(name="products_id", nullable=false, updatable=false) })
    private Set<Product> UserProducts = new HashSet(0);

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_wishes", catalog="toysonlineshoppingdb",
            joinColumns = {@JoinColumn(name="user_id", nullable=false, updatable=false) },
            inverseJoinColumns = {@JoinColumn(name="products_id", nullable=false, updatable=false) })
    private Set<Product> UserWishes = new HashSet(0);



    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_interest_category", catalog="toysonlineshoppingdb",
            joinColumns = {@JoinColumn(name="user_id", nullable=false, updatable=false) },
            inverseJoinColumns = {@JoinColumn(name="category_id", nullable=false, updatable=false) })
    private Set<Category> userInterestCategory = new HashSet(0);


    public User() {
    }
    public User(String email, String name, String password, Date birthdate, String job, String address, BigDecimal creditlimit, String imagename) {
        this.email = email;
        this.name = name;
        this.password = password;
        this.birthDate = birthdate;
        this.job = job;
        this.address = address;
        this.creditLimit = creditlimit;
        this.imagePath = imagename;
    }
    public User(String email, String name, String password, Date birthdate, String job, String address, BigDecimal creditlimit, String imagename, Set reviews, Set orderhistories, Set shoppingcarts, Set productses, Set productses_1) {
        this.email = email;
        this.name = name;
        this.password = password;
        this.birthDate = birthdate;
        this.job = job;
        this.address = address;
        this.creditLimit = creditlimit;
        this.imagePath = imagename;
        this.reviews = reviews;
        this.orderHistories = orderhistories;
        this.shoppingCarts = shoppingcarts;
        this.UserProducts = productses;
        this.UserWishes = productses_1;
    }



    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }



    public BigDecimal getCreditLimit() {
        return creditLimit;
    }

    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public Set getReviews() {
        return reviews;
    }

    public void setReviews(Set reviews) {
        this.reviews = reviews;
    }

    public Set getOrderHistories() {
        return orderHistories;
    }

    public void setOrderHistories(Set orderHistories) {
        this.orderHistories = orderHistories;
    }

    public Set getShoppingCarts() {
        return shoppingCarts;
    }

    public void setShoppingCarts(Set shoppingCarts) {
        this.shoppingCarts = shoppingCarts;
    }

    public Set getUserProducts() {
        return UserProducts;
    }

    public void setUserProducts(Set userProducts) {
        UserProducts = userProducts;
    }

    public Set getUserWishes() {
        return UserWishes;
    }

    public void setUserWishes(Set userWishes) {
        UserWishes = userWishes;
    }
}


